server:
  port: 8080
  servlet:
    context-path: /movies-web
  
spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
   
  datasource:
    platform: mysql
    url: "jdbc:mysql://localhost:3306/movieDB"
    username: spring
    password: password1234
    
# Edit to match your own file system
photoTempDir: "/home/ubersfeld/Pictures/tmp/"


#myhost: localhost
myhost: www.dominique-ubersfeld.com

myapp:
  chatroom:
    #url: "http://localhost:8080/movies-web/chat" 
    url: "http://www.dominique-ubersfeld.com:8080/movies-web/chat"        
  allowed:
    #origins: "http://localhost:8080"
    origins: "http://www.dominique-ubersfeld.com:8080"
  privateChatroom:
    #url: "http://localhost:8080/movies-web/chat" 
    url: "http://www.dominique-ubersfeld.com:8080/movies-web/privateChat"        
    